/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(features)'}/blogPost` | `/blogPost`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/accountDetails` | `/accountDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/loginPassword` | `/loginPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/signUp` | `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/post` | `/post`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(features)'}/blogPost` | `/blogPost`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(registration)'}/accountDetails` | `/accountDetails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(registration)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(registration)'}/loginPassword` | `/loginPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(registration)'}/signUp` | `/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/post` | `/post`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(features)'}/blogPost${`?${string}` | `#${string}` | ''}` | `/blogPost${`?${string}` | `#${string}` | ''}` | `${'/(registration)'}/accountDetails${`?${string}` | `#${string}` | ''}` | `/accountDetails${`?${string}` | `#${string}` | ''}` | `${'/(registration)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(registration)'}/loginPassword${`?${string}` | `#${string}` | ''}` | `/loginPassword${`?${string}` | `#${string}` | ''}` | `${'/(registration)'}/signUp${`?${string}` | `#${string}` | ''}` | `/signUp${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/post${`?${string}` | `#${string}` | ''}` | `/post${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(features)'}/blogPost` | `/blogPost`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/accountDetails` | `/accountDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/loginPassword` | `/loginPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registration)'}/signUp` | `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/post` | `/post`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
